name : Fetch Contest and Update DB

on :
    schedule:
        - cron: "*/10 * * * *"
    workflow_dispatch:

jobs:
  fetch_contests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install dependencies
      run: pip install -r requirements.txt
    
    - name: Create .env file from GitHub Secrets
      run: |
        echo "user=${{ secrets.USER }}" >> backend_contest_unify/.env
        echo "password=${{ secrets.PASSWORD }}" >> backend_contest_unify/.env
        echo "host=${{ secrets.HOST }}" >> backend_contest_unify/.env
        echo "port=${{ secrets.PORT }}" >> backend_contest_unify/.env
        echo "dbname=${{ secrets.DBNAME }}" >> backend_contest_unify/.env

    - name: Run backend_index.py
      working-directory: ./backend_contest_unify
      run: python backend_index.py
    
    - name: Show contest_fetcher.log
      run: cat backend_contest_unify/contest_fetcher.log || echo "Log file not found"

    - name: Upload contest_fetcher.log
      uses: actions/upload-artifact@v4
      with:
        name: fetcher_logs
        path: backend_contest_unify/contest_fetcher.log
